version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/common/files/.github/workflows"
      - "templates/**"
      - "/"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"
