version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/common/files/.github/workflows"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"
