repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-toml
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 84080c769d17e250eb32ac0d10662c7bf03ad346  # frozen: 0.31.3
  hooks:
    - id: check-dependabot
    - id: check-github-workflows
      args: ["--verbose"]
- repo: https://github.com/brokenpip3/pre-commit-hooks
  rev: dd7b3821637ba3c3a8628ad487fd84edec8006f2  # frozen: 0.0.1
  hooks:
    - id: github-actions-hash
      files: \.(yml|yaml)$
