repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-toml

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.1
  hooks:
    - id: check-dependabot
    - id: check-github-workflows
      args: ["--verbose"]
