repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-toml

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.1
  hooks:
    - id: check-dependabot
    - id: check-github-workflows
      args: ["--verbose"]

- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.12.0
  hooks:
    - id: reorder-python-imports

- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    types: [python]
    files: ^src/
    entry: pytest -v -s .
    language: system
    pass_filenames: false

  - id: ruff-format
    name: ruff-format
    types: [python]
    files: ^src/
    entry: ruff format
    language: system
    pass_filenames: false

  - id: ruff-check
    name: ruff-check
    types: [python]
    files: ^src/
    entry: ruff check --fix
    language: system
    pass_filenames: false
