name: CI

concurrency:
  group: "tests"
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  tests:
    if: github.event.pull_request.draft == false
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ["tests"]
    steps:

    - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      with:
        diagnostic-endpoint: ""

    - uses: DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4 # v9
      with:
        diagnostic-endpoint: ""

    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Test ${{ matrix.test }}
      run: nix develop . --command task ${{ matrix.test }}
