name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flake: [base, python-poetry]
    steps:
    - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      with:
        diagnostic-endpoint: ""
    - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
      with:
        diagnostic-endpoint: ""
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Init and check
      env:
        FLAKE: ${{ matrix.flake }}
      run: |
        mkdir tmp && cd tmp
        nix flake init -t ../#${FLAKE}
        git add .
        nix flake check
